let database = [
{
		"writer": "Buddhadeb Guha",
		"name": "ধোকার দোলনা",
       "language": "Bangla",
       "subject": "Novel",
		"page": "12",
		"link": "https://drive.google.com/file/d/1MV5h4EmP1lM6YwWTT5pZkoFr5heRFald/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Buddhadeb Guha",
		"name": "রুআহা",
       "language": "Bangla",
       "subject": "Adventure ",
		"page": "89",
		"link": "https://drive.google.com/file/d/1mkwWFJmBFwbN4pflC5-WZ6b7hmM0s5yx/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Buddhadeb Guha",
		"name": "Shooting Pal",
       "language": "Bangla",
       "subject": "Novel",
		"page": "8",
		"link": "https://drive.google.com/file/d/1RgZvEtCUQjuhd_xBK5seVm9XIdWTbxrP/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Buddhadeb Guha",
		"name": "সুবর্ণরেখা ও কাশ এর গল্প",
       "language": "Bangla",
       "subject": "Novel",
		"page": "14",
		"link": "https://drive.google.com/file/d/1jbKMITZ6qgpvL49kcNEnSRdcjrCXOJLA/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Buddhadeb Guha",
		"name": "সুদূর সকাল",
       "language": "Bangla",
       "subject": "Novel",
		"page": "32",
		"link": "https://drive.google.com/file/d/1ioWJ49aO7l3KJT8Ol40mAZh4rIvn-h7U/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Ordhek Jibon [Part.1]",
       "language": "Bangla",
       "subject": "Autobiography ",
		"page": "126",
		"link": "https://drive.google.com/file/d/1TwKkJKddlfTcS1eIawt0pb5fytiRlpI8/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Ordhek Jibon [Part.2]",
       "language": "Bangla",
       "subject": "Autobiography ",
		"page": "107",
		"link": "https://drive.google.com/file/d/1Vg7ZjUdUYQZ5bBQ1l9VVyyZAETaLs98Y/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Ordhek Jibon [Part.3]",
       "language": "Bangla",
       "subject": "Autobiography ",
		"page": "96",
		"link": "https://drive.google.com/file/d/1d7Yqbv3gOlCCzqCjOjQmnuyHSR4MK5k9/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Rani Katienar Dan Hat",
       "language": "Bangla",
       "subject": "Short Story",
		"page": "7",
		"link": "https://drive.google.com/file/d/12BaUTBLxMmD9gXQ3O2AyrtyUuZTSz2II/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Ek Komboler Niche",
       "language": "Bangla",
       "subject": "Romantic",
		"page": "9",
		"link": "https://drive.google.com/file/d/1QRS9UO65y_Bu2X-GDWXz1UY6FK9D9Mc8/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Rabi o som",
       "language": "Bangla",
       "subject": "Short Story ",
		"page": "5",
		"link": "https://drive.google.com/file/d/1BC073yz83RAOCRBxZ9ZjAJH5zHPn10ZG/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Amader Mahabharat",
       "language": "Bangla",
       "subject": "Religious ",
		"page": "308",
		"link": "https://drive.google.com/file/d/1VhdWog_X3MnBlbGXf4b9-MHWLTqUli68/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Amrriter Putra Konya",
       "language": "Bangla",
       "subject": "Novel",
		"page": "116",
		"link": "https://drive.google.com/file/d/1GvxmA3COGIeoVIJSHM08D8q3pAcJvehd/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Atmaprakash",
       "language": "Bangla",
       "subject": "Novel",
		"page": "137",
		"link": "https://drive.google.com/file/d/1Bm50AvFlnwSzD1-uuqufWYQbF3VJ0q0_/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Hothat Dekha",
       "language": "Bangla",
       "subject": "Novel",
		"page": "95",
		"link": "https://drive.google.com/file/d/1cRkFxU-pw_pr50dOU2Gh3HpoxFNOGy6P/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "jiboner epit opit",
       "language": "Bangla",
       "subject": "Novel",
		"page": "19",
		"link": "https://drive.google.com/file/d/1PoQWiTLkIWk0VRubSuFedpt9HQukW0_r/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Jol Jongoler Kabbo",
       "language": "Bangla",
       "subject": "Novel",
		"page": "97",
		"link": "https://drive.google.com/file/d/1yiL3ur8A7JKsT24Lg4JOSxXF-c4tB9Sg/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Moner Manush",
       "language": "Bangla",
       "subject": "Novel",
		"page": "47",
		"link": "https://drive.google.com/file/d/1lSy0IuS9sRxvH3YNY6ZkYDsfrVek7h56/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Nishshango Samrat",
       "language": "Bangla",
       "subject": "Novel",
		"page": "170",
		"link": "https://drive.google.com/file/d/1K-PfS2gw2nTe2ZdqWWX6jZTblzsKNnvF/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Porokiya Prem",
       "language": "Bangla",
       "subject": "Novel",
		"page": "245",
		"link": "https://drive.google.com/file/d/12nuZQ3YP7hMqwtAp8IRJqWKjEhkO5sGj/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Prothom Alo 01",
       "language": "Bangla",
       "subject": "Novel",
		"page": "288",
		"link": "https://drive.google.com/file/d/1CPMvucQcDEfKGIFqpSSxf5klrzdygmVz/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Rajbarir Rahasya",
       "language": "Bangla",
       "subject": "Thriller ",
		"page": "89",
		"link": "https://drive.google.com/file/d/1LTPyff1T_7Wb9Afe18iLiCS6ZGG-OaiQ/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "RoktoMangsho",
       "language": "Bangla",
       "subject": "Novel",
		"page": "65",
		"link": "https://drive.google.com/file/d/15O4If8pSSfWESAusscBDje_lKSsNnEzY/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Ruptan",
       "language": "Bangla",
       "subject": "Novel",
		"page": "108",
		"link": "https://drive.google.com/file/d/1BsqPMY75lcTfkC3GE2UtjfOJ3XkjNHlk/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Sei Somoy",
       "language": "Bangla",
       "subject": "Novel",
		"page": "702",
		"link": "https://drive.google.com/file/d/1a9m5eABCV0AgF5pGNS2XQ6fKDqmKXXfX/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Sera Goyenda Golpo By Sunil Gangopadhyay",
       "language": "Bangla",
       "subject": "Detective ",
		"page": "202",
		"link": "https://drive.google.com/file/d/1WiHNXZFAxco6-N2SDwCo0lFPFLA4Rq9l/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Shreshto Premer Uponnyash - Sunil Gangopadhyay",
       "language": "Bangla",
       "subject": "Novel",
		"page": "729",
		"link": "https://drive.google.com/file/d/1ZLxGqUEnrqBwJYo_NMlJYSDbyVQ1zDhN/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Sunil Gangopadhyay er Shreshtho Kobita",
       "language": "Bangla",
       "subject": "Poetry ",
		"page": "140",
		"link": "https://drive.google.com/file/d/1g297ra-UnehW2UWgaXuv_2nFXYD7D2_s/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Bhalobasha Prem Noi",
       "language": "Bangla",
       "subject": "Novel",
		"page": "65",
		"link": "https://drive.google.com/file/d/1iW0Mng9yz1W_kwjvFmAYrjNArhFam0DV/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Dui Nari Hate Tarbari",
       "language": "Bangla",
       "subject": "Novel ",
		"page": "14",
		"link": "https://drive.google.com/file/d/1uAsWJg9QWE_6U-ZIHXUlK0-XPlXdDlop/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Jomoj Kahini",
       "language": "Bangla",
       "subject": "Short Story",
		"page": "12",
		"link": "https://drive.google.com/file/d/11acV3pl5JmIIO5gBKhQP1RCsdLvfg1km/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Tin Nombor Cokh",
       "language": "Bangla",
       "subject": "Fiction",
		"page": "62",
		"link": "https://drive.google.com/file/d/11Y-WvXwiBmbfchsvqt3pBer5SUxnZ0Lk/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Akash Dossu",
       "language": "Bangla",
       "subject": "Science Fiction ",
		"page": "35",
		"link": "https://drive.google.com/file/d/1h3cWWzyI48j9dsgSvShWbgBKGxeBQvQ6/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Ami Keo Na",
       "language": "Bangla",
       "subject": "Novel",
		"page": "32",
		"link": "https://drive.google.com/file/d/19gm3nHizs3XL2bhN--v1XULyeXDy7SEh/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Chobighore Ondhokar",
       "language": "Bangla",
       "subject": "Novel",
		"page": "65",
		"link": "https://drive.google.com/file/d/1AZEbVoXeHf5CDnHmA4cgiZdnPvx7-NrV/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Dunga",
       "language": "Bangla",
       "subject": "Fiction ",
		"page": "99",
		"link": "https://drive.google.com/file/d/1sTW6avBIIdmntk3D5ZO-5Qf_HKNuTYUU/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Holde Barir Rohosya",
       "language": "Bangla",
       "subject": "Detective ",
		"page": "21",
		"link": "https://drive.google.com/file/d/1MG5sBk67gkC61e00JONf0amAfAyZbxmi/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Jolodossu",
       "language": "Bangla",
       "subject": "Novel",
		"page": "126",
		"link": "https://drive.google.com/file/d/1xZwIo9_Y0fE6DV8COb8I1f65pQvmk7Yg/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Sunil Gangopadhyay",
		"name": "Moner Manush",
       "language": "Bangla",
       "subject": "Novel",
		"page": "48",
		"link": "https://drive.google.com/file/d/1wHkzz2uDgywaLLD3V6t3FOa3w0u2K0Wg/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "আমেরিকায় টিন টিন",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1pkGpxJB9_OlrCA127ZM6kVEeB7AH7n6W/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "আশ্চর্য ঊল্কা",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/16xa0LD4uvbQEXrC_MCtHEBD4b7J3DStk/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "কঙ্গোয় টিন টিন",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1xMzsWMgcZzLCkcyEJSZqu2qyNseMa9-j/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "কাঁকড়া রহস্য",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1I5bi4I-_adzTWrXtP0NXS2-u6b1r8132/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "কান ভাঙ্গা মূর্তি",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1E-1c2H7c7z-LtGnzKmdV4qsKPTkCR_qT/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "কাল সোনার দেশ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1ZwssI1yDsVxCtEJlIDNcPxk5UAGPxnVP/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "চন্দ্রালোকে অভিযান",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/116q2e549_O4jaNN48ialqFHbv5SY0eMB/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "চাঁদে টিন টিন",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1bXPP4JgQQu0oiZNpB4JFTY_L5s51NHcQ/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "ফ্লাইট ৭১৪",
       "language": "Bangla",
       "subject": "Comics",
		"page": "56",
		"link": "https://drive.google.com/file/d/1mHGmMhMZOq9w2Szx1yW_CSieNSVKdRlx/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "বিপ্লবিদের দঙ্গলে",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1vDyFoK1St5nxvBL7sIOUMg2owdgd8pIL/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "বিপ্লবিদের দঙ্গলে",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1vDyFoK1St5nxvBL7sIOUMg2owdgd8pIL/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "বোম্বেটে জাহাজ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1MV3_lTyrENWLlwAt5TEuYaFofIzNnccZ/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "মমির অভিশাপ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1k4bDmPYLG0KapUyHVeoFHPgMHIskQsHZ/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "লাল বোম্বেটের গুপ্তধন",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1VgYd-iLR31GXTZ_6ul0CgYCg8n9XYBTa/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "Suryadeber Bandi",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1rSUSVWmIKv3msuUBGuoGdzM8pI48hnwT/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "Calculus er kando",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1sp7KRRqBvOZM1L6rIbtLt4Rj3_E6Aft7/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "Nil Kamal",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1G0Mvcsz1DQtGQVn1TAYYEBqOgESUvfIF/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "Pharaoh-er Churut",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1Gq8hAZZWKp3sVIIwg2D2e8eBHd5R6VnL/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "The Black Island",
       "language": "Bangla",
       "subject": "Comics",
		"page": "64",
		"link": "https://drive.google.com/file/d/1na0POJAAdbOXzWNJwqrYsCsvuX9Lv22l/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Hergé",
		"name": "TIBBOT E TINTIN",
       "language": "Bangla",
       "subject": "Comics",
		"page": "61",
		"link": "https://drive.google.com/file/d/1hJfKQC_WxHe2O8o5k8bKQAQeZW-JhzI1/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Ching Fu",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1b-9Uv95mPnbPUltdnqFRhT8aB6PXVDq6/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Endur Shikar",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1_vSoFGXf6-mpBsy-6YjWaZLwJiQWoeee/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Cricket",
       "language": "Bangla",
       "subject": "Comics",
		"page": "2",
		"link": "https://drive.google.com/file/d/13Qnfn8KaU9hzQDNDaikWhR4p0uBU7f9M/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Chachajir Barite Chor",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1_UVOc9Vgs75hJnbN3y52hBALZGtwS90I/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Bohu Mullay Nacless",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1nw0fwsLlaSgLmJi1EaxabCkr8KaOv-FM/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Antarikher Football",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1pxF_GN2KEqIEZe7s_ul209qb9ufCtPvz/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Ashcharya Dip",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1kITuQK-2LNohtPRuZqEaAhS1cPtd8wxi/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Electrick shok",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1a5boFsSZ0x1X0Ww4NLMCcERO1Rl3NkSb/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Packet",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1l_Jproh5oYX3-_DtBh9yaZSgr-e5cUN4/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Nekhre Ar Bagh",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1j8yLU6NLYsK2J0jAHNzLcdrUBFFSS0-q/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Trake Loha",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/18TCev5Bi0atfTugoDy5sAuYkfhuprrSe/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Rolton Polton",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1RvhjeZACq9chJit-RWaOGA4Rdw1nDMLQ/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Lej Wala Doitto",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1qANcjckm8Jrk_0S5CWeByrKJsI4nYJDt/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Nababorsher protiga",
       "language": "Bangla",
       "subject": "Comics",
		"page": "3",
		"link": "https://drive.google.com/file/d/1XbFPZ47v8nH_hlKhWdVNyTKwiVpjvpsB/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Chacha Choudhury Ar Deadly Dan",
       "language": "Bangla",
       "subject": "Comics",
		"page": "42",
		"link": "https://drive.google.com/file/d/1wYX1bgioe4WtgkGLxmuxzAv3j9xakqv4/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Chacha Chowdhry Aar Rakar Jobab-HQ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "46",
		"link": "https://drive.google.com/file/d/174rTHKU6tmpfQkeX3LL9x8eqZl8zP3d-/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Chacha Chowdhry Aar Rakar Jobab",
       "language": "Bangla",
       "subject": "Comics",
		"page": "46",
		"link": "https://drive.google.com/file/d/1ksjjvjmobl69Pqs-D4M5qHH8UKbQmNAS/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Chacha Chowdhury Aar Bideshi Agent",
       "language": "Bangla",
       "subject": "Comics",
		"page": "46",
		"link": "https://drive.google.com/file/d/1YmIQDLMwiL8vPxBI176Hbue_l65oOlGQ/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "Chacha Chowdhury Aar Kango",
       "language": "Bangla",
       "subject": "Comics",
		"page": "61",
		"link": "https://drive.google.com/file/d/11jHCTlxlPv47HK4eOTZLbqYW3kmvqqvG/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "দায়িত্ব",
       "language": "Bangla",
       "subject": "Comics",
		"page": "57",
		"link": "https://drive.google.com/file/d/1f2IUEjQdg0Rm5jparcv3KmYbP3HuY4cU/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "রাকার আক্রমণ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "24",
		"link": "https://drive.google.com/file/d/11g3GaMk-le3hiBKQi6HmQq07TdemK-KE/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "শিশু চিত্র তারকা ববি",
       "language": "Bangla",
       "subject": "Comics",
		"page": "23",
		"link": "https://drive.google.com/file/d/11cFJQyLePeFKCHmZEbIIXlMcopZ4Q3NT/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর আফলাতুন",
       "language": "Bangla",
       "subject": "Comics",
		"page": "59",
		"link": "https://drive.google.com/file/d/100IRcfMuNeMnmV17hCZjLkB3CKGpor7-/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর রাকার চ্যালেঞ্জ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "63",
		"link": "https://drive.google.com/file/d/1VY8vYYizxCrHlbL76cFQQ_Ckeki7wOuH/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী - সাইবার ক্রাইম",
       "language": "Bangla",
       "subject": "Comics",
		"page": "47",
		"link": "https://drive.google.com/file/d/11zQ54ubpki2elWQpPzEwj7oSzYYSU4Ol/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর আফলাতুন",
       "language": "Bangla",
       "subject": "Comics",
		"page": "59",
		"link": "https://drive.google.com/file/d/1q4ZQVjnG_u8DYaAZdixxBTCCDX0-2mW2/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর ওয়ার্ল্ড কাপ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "45",
		"link": "https://drive.google.com/file/d/15xUuqKhrgjWu4Tqepns5oghpArMpUF2Z/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর ওয়ার্ল্ড কাপ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "45",
		"link": "https://drive.google.com/file/d/1yY9tTza7tub6YqmYJc7mDhD7iFCD-UTv/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর কাঙ্গো",
       "language": "Bangla",
       "subject": "Comics",
		"page": "61",
		"link": "https://drive.google.com/file/d/1RiizBsDZJOAN5rkusBnAfItuOE4bfAJQ/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর নীল হীরে",
       "language": "Bangla",
       "subject": "Comics",
		"page": "49",
		"link": "https://drive.google.com/file/d/1j2sHfgEYA77Avmep_iXzmWpLEm--CPlY/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর বিদেশী এজেন্ট",
       "language": "Bangla",
       "subject": "Comics",
		"page": "46",
		"link": "https://drive.google.com/file/d/1OcPiFwRfADMqwW5FVDR4JGzveryfJ5eM/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর বেনারসী জোচ্চোর",
       "language": "Bangla",
       "subject": "Comics",
		"page": "49",
		"link": "https://drive.google.com/file/d/1-ibTtwCXLNofP1Ps9tGGTdfPjn1Fp7F8/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর মিস ইউনিভার্স",
       "language": "Bangla",
       "subject": "Comics",
		"page": "41",
		"link": "https://drive.google.com/file/d/1tni6NlrrRNod2OpM32OWiKLSVw-t1RLv/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর রাকার খেলা",
       "language": "Bangla",
       "subject": "Comics",
		"page": "45",
		"link": "https://drive.google.com/file/d/1uGSR_4tWJWi-dwGuZV4GxJM08P9AR4iw/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর রাকার চ্যালেঞ্জ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "63",
		"link": "https://drive.google.com/file/d/1JiEdMdWy-Fxx1agqYZrygJlJfjw2Mwz2/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর স্কাই ডাইভার",
       "language": "Bangla",
       "subject": "Comics",
		"page": "46",
		"link": "https://drive.google.com/file/d/1CUNfrWfUIjOfYeBw6GgsG7FvnxVRqix6/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী আর হাইজ্যাকার",
       "language": "Bangla",
       "subject": "Comics",
		"page": "41",
		"link": "https://drive.google.com/file/d/1kiWtHQR-v_XjYkNsTmfl9J5Bdbl2oZaC/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী ও চম্পত সম্পত",
       "language": "Bangla",
       "subject": "Comics",
		"page": "46",
		"link": "https://drive.google.com/file/d/1_QhjIN_N1FzI4YPtn2yEIxiW_JDYChcH/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী ও ব্যাঙ্ক লুঠেরা",
       "language": "Bangla",
       "subject": "Comics",
		"page": "62",
		"link": "https://drive.google.com/file/d/1vVg4fTi90VLIVjnFY3AsALmh-zLtqG7U/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী ও ম্যাডাম জোরো",
       "language": "Bangla",
       "subject": "Comics",
		"page": "45",
		"link": "https://drive.google.com/file/d/1BB0QySGdbT1Sy4PYgpMoxnZ1f065AGXE/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "চাচা চৌধুরী টোকিওতে",
       "language": "Bangla",
       "subject": "Comics",
		"page": "45",
		"link": "https://drive.google.com/file/d/1Lp3oxWK9B0NfwzI4Z36eewaReMRlsu2F/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "০২ চাচা চৌধুরী ও রাকার পুনরাগমন",
       "language": "Bangla",
       "subject": "Comics",
		"page": "63",
		"link": "https://drive.google.com/file/d/18Xx4Ru0LzKi8HuuNtPAe7fyy2PulRIFh/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "০৩ চাচা চৌধুরী ও রাকার প্রতিশোধ",
       "language": "Bangla",
       "subject": "Comics",
		"page": "61",
		"link": "https://drive.google.com/file/d/1yt48g1I2atApMD7oWJBbPOdlD-REdv4w/view?usp=drivesdk",
       "terms": "Literature" ,
   },
{
		"writer": "Pran Kumar Sharma",
		"name": "০১ চাচা চৌধুরী আর রাকা",
       "language": "Bangla",
       "subject": "Comics",
		"page": "62",
		"link": "https://drive.google.com/file/d/1XUA77CbHn-LNd15B6DAUZXB_AVk04Xav/view?usp=drivesdk",
       "terms": "Literature" ,
   },

	{
		"writer": "Elisabeth Tova Bailey",
		"name": "Sound of a Wild Snail Eating",
       "language": "English",
       "subject": "Science",
		"page": "110",
		"link": "https://drive.google.com/file/d/1KrcZjpnfeCiigSUDQEDMBcA-y2QCI5Fr/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Gene Wallenstein",
		"name": "Pleasure Instinct",
       "language": "English",
       "subject": "Science",
		"page": "171",
		"link": "https://drive.google.com/file/d/1PKfRocLxrv97cC6v4QVvXPtOOzaDXraQ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "David R. Montgomery",
		"name": "Dirt The Erosion of Civilizations",
       "language": "English",
       "subject": "Science",
		"page": "354",
		"link": "https://drive.google.com/file/d/1C7twE3lTrJMMH2FZJVlRtevJQ9KsHh6_/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Edward Dolnick",
		"name": "Clockwork Universe Isaac Newton, the Royal Society and the Birth of the Modern World",
       "language": "English",
       "subject": "Science",
		"page": "407",
		"link": "https://drive.google.com/file/d/1r7xDT2EZ5reCmlhPYFg91MayNSHjYkGJ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Eric N. Simons",
		"name": "Darwin Slept Here",
       "language": "English",
       "subject": "Science",
		"page": "133",
		"link": "https://drive.google.com/file/d/1msGGaI3XLyn0qD9MvKUYz2TWiU7cJOQ7/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "David Dobbs",
		"name": "Reef Madness",
       "language": "English",
       "subject": "Science",
		"page": "302",
		"link": "https://drive.google.com/file/d/1026GDnq5LsCuFwgdvWe33mL0-XFUtnUM/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Dava Sobel",
		"name": "More Perfect Heaven",
       "language": "English",
       "subject": "Science",
		"page": "257",
		"link": "https://drive.google.com/file/d/1hoRo9wKtJ-aQlmEldWpN1x7IHkgNrsDR/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Charles Seife",
		"name": "Sun in a Bottle",
       "language": "English",
       "subject": "Science",
		"page": "210",
		"link": "https://drive.google.com/file/d/1Hsu1kVKgoWYYltwtTUf3S491WC1dkVEs/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Carl Sagan",
		"name": "Demon - Haunted World Science as a Candle in the Dark",
       "language": "English",
       "subject": "Science",
		"page": "457",
		"link": "https://drive.google.com/file/d/18irmeJkfzfqhYqsZNofER9vpv8cABc4Q/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Carl Sagan",
		"name": "Pale Blue Dot",
       "language": "English",
       "subject": "Science",
		"page": "298",
		"link": "https://drive.google.com/file/d/1TW48dySyEETQQdzf-eK5PkUtrYvC1XYP/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Brian Greene",
		"name": "Elegant Universe",
       "language": "English",
       "subject": "Science",
		"page": "428",
		"link": "https://drive.google.com/file/d/1AvOkrO_Q7LQkOfj3T5Hg3-JNtywDB85U/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Brian Greene",
		"name": "Hidden Reality",
       "language": "English",
       "subject": "Science",
		"page": "420",
		"link": "https://drive.google.com/file/d/1sA834xgL3wudfhY74Pnz7EXkny945_eR/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Carl Sagan",
		"name": "Cosmos",
       "language": "English",
       "subject": "Science",
		"page": "359",
		"link": "https://drive.google.com/file/d/16lR2Nxs1wrqksPY-5AzGE0zPF72z3B3X/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Gemmell, Jim",
		"name": "Total Recall",
       "language": "English",
       "subject": "Science",
		"page": "313",
		"link": "https://drive.google.com/file/d/1a0THLNxptTrWX3_o8E12TNHICQK6pd2S/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "David Quammen",
		"name": "Song of the Dodo Island Biogeography in an Age of Extinctions",
       "language": "English",
       "subject": "Science",
		"page": "896",
		"link": "https://drive.google.com/file/d/11-D0R1PAAJXFGYaVNQJsaas-awc7nvZZ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Brian Cox",
		"name": "Why Does E=mc2",
       "language": "English",
       "subject": "Science",
		"page": "136",
		"link": "https://drive.google.com/file/d/1v9L6t38ye03biifsHwZEGiOJWPB3mfLC/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Bill Bryson",
		"name": "Seeing Further",
       "language": "English",
       "subject": "Science",
		"page": "424",
		"link": "https://drive.google.com/file/d/1epKzeyBqIMElAmUq2pW1nYCJB6KRmEtk/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Bernd Heinrich",
		"name": "Winter World The Ingenuity of Animal Survival",
       "language": "English",
       "subject": "Science",
		"page": "320",
		"link": "https://drive.google.com/file/d/1YApRXTAC2uUoDYQ8Ye-noOScFWvrzInw/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Barbara Strauch",
		"name": "Secret Life of the Grown up Brain",
       "language": "English",
       "subject": "Science",
		"page": "159",
		"link": "https://drive.google.com/file/d/1FfBKtmcUKBP51lRMUoOF36LaEV61w3_C/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Adam Greenfield",
		"name": "Everyware",
       "language": "English",
       "subject": "Science",
		"page": "258",
		"link": "https://drive.google.com/file/d/18Y29LcfBwPkuPl9QkH-Dexg8BsgL_sWQ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Andrew Newberg, M. D. & Mark Robert Waldman",
		"name": "How God Changes Your Brain",
       "language": "English",
       "subject": "Science",
		"page": "455",
		"link": "https://drive.google.com/file/d/1fFNA7QM1pTtJ2WuSO2ctXhSnr89sNIoe/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Andrew Newberg, M. D. & Mark Robert Waldman",
		"name": "How God Changes Your Brain",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1fFNA7QM1pTtJ2WuSO2ctXhSnr89sNIoe/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Jonathan Weiner",
		"name": "Long for This World",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1lGWhkBG_p7DLmdnyLze3SNX4_g2qvqC4/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Jonah Lehrer",
		"name": "How We Decide",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/11XT7rfMJ1ckuTMUqSgmrZ9Zj_gHTp9o4/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Annie Leonard",
		"name": "STORY OF STUFF",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1K5QQCQLseW_C5XEomOuG7jzAAYeSjKY3/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Jonah Lehrer",
		"name": "Proust Was a Neuroscientist",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1HWxKmyN1Oi4P9vJSqG6dqhTsXNJReQbu/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "John Vaillant",
		"name": "Golden Spruce",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1fgTgpoA2uUvXO7FO_ksqBDgDmGHdo-iR/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "John M. Barry",
		"name": "Great Influenza",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1HqFOS_IkBxUzAWCfBztzyxsII-bNqPlU/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "John D. Barrow",
		"name": "Book of Nothing",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1MM-C41L-oIDz_9Q6hBh5FuFk6uo7Ou6d/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "James Prosek",
		"name": "Eels",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1R5R5h4AZ6ps1Kmx46EaDh4VdwNwQxsb3/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "James Burke",
		"name": "Day the Universe Changed",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1WSK04WTZE8tH0CA8Th9xz2gTYoGDRRV1/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "James Gleick",
		"name": "Genius The Life and Science of Richard Feynman",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1Ya2SuJliJrkDHja98xKl9_hDZHKZUyFf/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "James Gleick",
		"name": "Chaos",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/10qUhFpmvNeDzZHzmaxmcXDZIWb3rWe17/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Jerry A. Coyne",
		"name": "Why Evolution Is True",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1_4GXsNgar27UZFvWm3YG7uBMYYEmvnaY/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Jeff Benedict",
		"name": "No Bone Unturned",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1I7dVhDeTVHa9cLbzL9P0O5Dm5k-O-ELD/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Ian Mccallum",
		"name": "Ecological Intelligence",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1jsZpagJD2QFcOudAD633GSnbClOBb8Gi/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Tom Vanderbilt",
		"name": "Traffic Why We Drive the Way We Do (And What It Says About Us)",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/10-hQx0s_vhESItuP5fpmYDWQVen_uk6Y/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Gerd Gigerenzer",
		"name": "Gut Feelings",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1SlffcIEcu4etf9jwvrjYNDwz5O2UcayO/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Joseph Gies",
		"name": "Cathedral - Forge and Waterwheel",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1cy0WYM062WFVGYS7MwUR3pSUyp6PnR11/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "George Friedman",
		"name": "Next Decade",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1x1GwIxMNZfSFOIioDPShRZRJSBMXgLGT/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "H. N. Pollack",
		"name": "World Without Ice",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1Jv-Xfn_jntE223zwItLK9pni4bmVyzct/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Geoffrey Beattie",
		"name": "Why Aren't We Saving the Planet A Psycholotist's Perspective",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/10ngTsCURLOl8MqpYnk12Lk63Ixie9sJz/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Hattie Ellis",
		"name": "Sweetness and Light",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1idg_eS9hbJN2SxAIPisPHfhZ5q9aBtVD/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Henry Petroski",
		"name": "Evolution of Useful Things",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1pzJFcXFTAlugFoCzLvcec1SBITYnIhMg/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Heidi Cullen",
		"name": "Weather of the Future",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1kOtn5hXc_7Zz9hjjcLPp08xBJur3xNAP/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Iain McGilchrist",
		"name": "MASTER AND HIS EMISSARY",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1GTeGqm-0zuvl8p4sU07Xqs2Lkk3xPOhE/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Isaac Asimov",
		"name": "Extraterrestrial Civilizations",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1JXgRs4oz37hjxBO9430WueTekDsoavBW/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Henry Schlesinger",
		"name": "Battery",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1VdOL-kY8QXYhdII1S-0NSe3T9iBdKMQ9/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "John McWhorter",
		"name": "Our Magnificent Bastard Tongue",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1I174jz_rsC4Dedi9xZ0Ue2jRb8pTnDmI/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Jon Queijo",
		"name": "Breakthrough! How the 10 Greatest Discoveries in Medicine Saved Millions and Changed Our View of the World",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1ijYGD4u7ipccszxp2l-Ui75oFTzgswUp/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Juliet Eilperin",
		"name": "Demon Fish",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1d91KQ-VYwo45NDzFYW46lgk6961zKhtQ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Hugh Raffles",
		"name": "Insectopedia",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1nyl6NnxNMtWk1VbThpXOKcTdWKrwqmig/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Lawrence Maxwell Krauss",
		"name": "physics of Star Trek",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1MQrb1SEYrl_hNQFgaXEJv-yjcxuMnYof/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Leonard Mlodinow",
		"name": "Drunkard's Walk",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1WmUjwDoUnyShCSejbZpZoXmnfSSJo4Ms/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Marc Bekoff",
		"name": "Animal Manifesto",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/19s4C8XBEk-yHR5Kvwq5sgu9oR6YcWHQZ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Barbara Bradley Hagerty",
		"name": "Fingerprints of God",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1wZm3N0Snr4sOLRw_illGqaA2IPcoKx1z/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Alan Weisman",
		"name": "World Without Us",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1LmZrXcAOanh9ENtdOKZY_Y1bw_HTYGTQ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Ben Goldacre",
		"name": "2008 - Bad Science",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/11GCnOtAj12Tvbf1zbFLwADtmDPUvHz4i/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Henry Petroski",
		"name": "Engineers of Dreams",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1xKp68u0twnZKeC8pY6_p-c0Re49VMsVU/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Bernd Heinrich",
		"name": "Summer World",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1tE1AVXs33uZ5HWUqRASUiusT-cndlM7W/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Bill Bryson",
		"name": "Short History of Nearly Everything",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1vwn_gEupscATRt5iRmzylRyDZHv8RkTu/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Professor Brian Cox & Andrew Cohen",
		"name": "Wonders of the Universe",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/13YW63nMQJRsgsdncQrm47RCSoCOxoBOq/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Brian Christian",
		"name": "Most Human Human",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1dhgVH-0kEuy_nV64grhroaEegwwxQttl/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Charles Darwin",
		"name": "Origin of Species",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1thfJN9o_pkv6D3CKFBeod1eaxhdzg1H6/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Cathy N. Davidson",
		"name": "Now You See It",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1hdbmViRop1QrCckclEinDSZoVj7lOI40/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Carl Zimmer",
		"name": "Planet of Viruses",
       "language": "English",
       "subject": "Science",
		"page": " ",
		"link": "https://drive.google.com/file/d/1cMfWermXVXNYvR458uKI_cK93ee6B7dq/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Christopher Cokinos",
		"name": "Fallen Sky",
       "language": "English",
       "subject": "Science",
		"page": "416",
		"link": "https://drive.google.com/file/d/1XF_kLoBQn18F6kjW3EswwyJAJU5NIB1r/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Christopher Hadnagy",
		"name": "Social Engineering",
       "language": "English",
       "subject": "Science",
		"page": "471",
		"link": "https://drive.google.com/file/d/1gC0-cPvhWNfNWQR5F-eAu0Wzoxh5PWCJ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Christian Parenti",
		"name": "Tropic of Chaos",
       "language": "English",
       "subject": "Science",
		"page": "232",
		"link": "https://drive.google.com/file/d/1PaUSDNVvnGw4gl8DDI-DMnsl3zlKLeDR/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Daniel J. Boorstin",
		"name": "Discoverers",
       "language": "English",
       "subject": "Science",
		"page": "880",
		"link": "https://drive.google.com/file/d/1E58iIKfNg0SfOE3kL1NJkPS41D569cpz/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Douglas R. Hofstadter",
		"name": "I Am a Strange Loop",
       "language": "English",
       "subject": "Science",
		"page": "373",
		"link": "https://drive.google.com/file/d/1sGR1iysiL8SsIgInHerRAplHfMfSYjZ7/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Dan Parry",
		"name": "Moonshot",
       "language": "English",
       "subject": "Science",
		"page": "353",
		"link": "https://drive.google.com/file/d/1aa89vPTRh3G6kX_D2GzHWAmav7SiSoEn/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Dava Sobel",
		"name": "Galileo's Daughter",
       "language": "English",
       "subject": "Science",
		"page": "393",
		"link": "https://drive.google.com/file/d/1UXFn8sK_Hr_k7Jo6qozx8kfmZpTbmzxF/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Dava Sobel",
		"name": "Longitude",
       "language": "English",
       "subject": "Science",
		"page": "320",
		"link": "https://drive.google.com/file/d/1mc2j42-S_D3OPXMQcHnslUJjP2PwwGlJ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "David Quammen",
		"name": "Natural Acts",
       "language": "English",
       "subject": "Science",
		"page": "320",
		"link": "https://drive.google.com/file/d/1mc2j42-S_D3OPXMQcHnslUJjP2PwwGlJ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "David Deutsch",
		"name": "Beginning of Infinity",
       "language": "English",
       "subject": "Science",
		"page": "587",
		"link": "https://drive.google.com/file/d/1MgTNbxD-bl3yfGeHJ44F4lWV_8eaILJL/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Amy Stewart",
		"name": "Wicked Plants",
       "language": "English",
       "subject": "Science",
		"page": "246",
		"link": "https://drive.google.com/file/d/1jxoyRs8EBJ6cEw394zZtsweIEFvkI4Ly/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Thomas Metzinger",
		"name": "Ego Tunnel",
       "language": "English",
       "subject": "Science",
		"page": "349",
		"link": "https://drive.google.com/file/d/12KEdMJDMFgpeJ_-FkefcL0h2cXc8d0U1/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Timothy Ferris",
		"name": "Coming of Age in the Milky Way",
       "language": "English",
       "subject": "Science",
		"page": "578",
		"link": "https://drive.google.com/file/d/1MvyinYH0HSCLwAc0ixfojquro2VN6NWX/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Sam Kean",
		"name": "Disappearing Spoon And Other True Tales of Madness, Love and e World from the Periodic Table of the Elements",
       "language": "English",
       "subject": "Science",
		"page": "339",
		"link": "https://drive.google.com/file/d/1d4N9D3YDpnBwh2-qOreNIEG3XXX4oA1o/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Robert Wolke",
		"name": "What Einstein Told His Barber More Scientific Answers to Everyday Questions",
       "language": "English",
       "subject": "Science",
		"page": "315",
		"link": "https://drive.google.com/file/d/1AxoScx90ZzdzrFGnyDuo1j1XFOjcVtBz/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Robert Oerter",
		"name": "Theory of Almost Everything",
       "language": "English",
       "subject": "Science",
		"page": "241",
		"link": "https://drive.google.com/file/d/1sGr1_fghKZ8vOWgh1k0eh67lLFMOdKl5/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Richard Dawkins",
		"name": "Unweaving the Rainbow",
       "language": "English",
       "subject": "Science",
		"page": "327",
		"link": "https://drive.google.com/file/d/17rXYZMIabwoWi2BTfQn4JGi6RUTB-z2o/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Paul Gilding",
		"name": "Great Disruption",
       "language": "English",
       "subject": "Science",
		"page": "317",
		"link": "https://drive.google.com/file/d/1uedZZasoRLSCKK8byf67hjzGi9CltaOa/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Paul A. Offit M.D",
		"name": "Deadly Choices How the Anti Vaccine Movement Threatens Us All",
       "language": "English",
       "subject": "Science",
		"page": "326",
		"link": "https://drive.google.com/file/d/1_x3fX3knwej2eaJbupv3MujCZkUXgrpH/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Sam Harris",
		"name": "Moral Landscape How Science Can Determine Human Values",
       "language": "English",
       "subject": "Science",
		"page": "352",
		"link": "https://drive.google.com/file/d/1McDIixBP0fp2mN8bl0lqHzoS9NWpRlNJ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Michael Specter",
		"name": "Denialism How Irrational Thinking Hinders Scientific Progress Harms the Planet and Threatens Our Lives",
       "language": "English",
       "subject": "Science",
		"page": "240",
		"link": "https://drive.google.com/file/d/1qumGKpvtiIlTXt8meW7huZyMSPJBhUoY/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Mike Brown",
		"name": "How I Killed Pluto and Why It Had It Coming",
       "language": "English",
       "subject": "Science",
		"page": "207",
		"link": "https://drive.google.com/file/d/1NQ8HcxsfiBr-bwDvxUaS7ExgNLdzU38B/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Molly Caldwell Crosby",
		"name": "American Plague",
       "language": "English",
       "subject": "Science",
		"page": "218",
		"link": "https://drive.google.com/file/d/1t0Jc8wsnFiCHjhsFHEhOEAyET8PqLTPQ/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Philip C. Plait",
		"name": "Bad Astronomy Misconceptions and Misuses Revealed From Astrology to the Moon Landing 'Hoax'",
       "language": "English",
       "subject": "Science",
		"page": "300",
		"link": "https://drive.google.com/file/d/1o4_QP0JBJ5IF3jMxqY75ayslZxhx7Qwt/view?usp=drivesdk",
       "terms": "Scientific" ,
   },
{
		"writer": "Michio Kaku",
		"name": "Physics of the Future How Science Will 
